"""0001_initial_schema

Revision ID: 1e5c879d0851
Revises: 
Create Date: 2026-08-20 12:48:18.092121

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e5c879d0851'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants'))
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_audit_events_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index(op.f('ix_audit_events_tenant_id'), 'audit_events', ['tenant_id'], unique=False)
    op.create_index('ix_audit_tenant_entity', 'audit_events', ['tenant_id', 'entity', 'entity_id'], unique=False)
    op.create_table('export_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('artifact_uri', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_export_runs_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_export_runs'))
    )
    op.create_index(op.f('ix_export_runs_tenant_id'), 'export_runs', ['tenant_id'], unique=False)
    op.create_table('import_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('errors', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_import_runs_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_runs'))
    )
    op.create_index(op.f('ix_import_runs_tenant_id'), 'import_runs', ['tenant_id'], unique=False)
    op.create_table('months',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('closed_by', sa.String(length=64), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('month BETWEEN 1 AND 12', name=op.f('ck_months_month_in_range')),
    sa.CheckConstraint('revision >= 0', name=op.f('ck_months_revision_non_negative')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_months_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_months')),
    sa.UniqueConstraint('tenant_id', 'year', 'month', name='uq_months_tenant_year_month')
    )
    op.create_index(op.f('ix_months_tenant_id'), 'months', ['tenant_id'], unique=False)
    op.create_table('outbox_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('FIXTURE_INGEST', 'TENANT_BOOTSTRAP', 'NOOP')", name=op.f('ck_outbox_jobs_outbox_kind_enum')),
    sa.CheckConstraint("status IN ('PENDING', 'RUNNING', 'DONE', 'FAILED')", name=op.f('ck_outbox_jobs_outbox_status_enum')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_outbox_jobs_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_jobs')),
    sa.UniqueConstraint('idempotency_key', name='uq_outbox_idempotency')
    )
    op.create_index(op.f('ix_outbox_jobs_tenant_id'), 'outbox_jobs', ['tenant_id'], unique=False)
    op.create_table('stores',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('company_code', sa.String(length=32), nullable=False),
    sa.Column('internal_code', sa.String(length=32), nullable=False),
    sa.Column('external_code', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_stores_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stores')),
    sa.UniqueConstraint('tenant_id', 'internal_code', name='uq_stores_tenant_internal')
    )
    op.create_index(op.f('ix_stores_tenant_id'), 'stores', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_users_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_users_tenant_email')
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('people',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('internal_code', sa.String(length=32), nullable=False),
    sa.Column('external_code', sa.String(length=64), nullable=True),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('home_store_id', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['home_store_id'], ['stores.id'], name=op.f('fk_people_home_store_id_stores')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_people_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_people')),
    sa.UniqueConstraint('tenant_id', 'internal_code', name='uq_people_tenant_internal')
    )
    op.create_index(op.f('ix_people_home_store_id'), 'people', ['home_store_id'], unique=False)
    op.create_index(op.f('ix_people_tenant_id'), 'people', ['tenant_id'], unique=False)
    op.create_table('sales_store_day',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('store_id', sa.String(length=64), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('generation', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('source_ref', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_sales_store_day_store_id_stores')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_sales_store_day_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_store_day')),
    sa.UniqueConstraint('tenant_id', 'store_id', 'business_date', 'generation', name='uq_sales_store_day_generation')
    )
    op.create_index(op.f('ix_sales_store_day_store_id'), 'sales_store_day', ['store_id'], unique=False)
    op.create_index(op.f('ix_sales_store_day_tenant_id'), 'sales_store_day', ['tenant_id'], unique=False)
    op.create_table('sheet_bindings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('store_id', sa.String(length=64), nullable=False),
    sa.Column('spreadsheet_id', sa.String(length=128), nullable=False),
    sa.Column('sheet_name_grila', sa.String(length=64), nullable=False),
    sa.Column('sheet_name_pontaj', sa.String(length=64), nullable=False),
    sa.Column('generation', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_sheet_bindings_store_id_stores')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_sheet_bindings_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sheet_bindings')),
    sa.UniqueConstraint('store_id', name='uq_sheet_binding_store')
    )
    op.create_index(op.f('ix_sheet_bindings_store_id'), 'sheet_bindings', ['store_id'], unique=False)
    op.create_index(op.f('ix_sheet_bindings_tenant_id'), 'sheet_bindings', ['tenant_id'], unique=False)
    op.create_table('sheet_projection_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('store_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_success_generation', sa.String(length=32), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_sheet_projection_runs_store_id_stores')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_sheet_projection_runs_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sheet_projection_runs'))
    )
    op.create_index(op.f('ix_sheet_projection_runs_store_id'), 'sheet_projection_runs', ['store_id'], unique=False)
    op.create_index(op.f('ix_sheet_projection_runs_tenant_id'), 'sheet_projection_runs', ['tenant_id'], unique=False)
    op.create_table('epay_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('store_id', sa.String(length=64), nullable=False),
    sa.Column('person_id', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('raw_value', sa.String(length=64), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('UNDER_50', 'AT_OR_OVER_50')", name=op.f('ck_epay_observations_epay_category_enum')),
    sa.CheckConstraint('value IS NULL OR (value >= 0 AND value <= 10)', name=op.f('ck_epay_observations_epay_value_range')),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_epay_observations_person_id_people')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_epay_observations_store_id_stores')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_epay_observations_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_epay_observations'))
    )
    op.create_index(op.f('ix_epay_observations_person_id'), 'epay_observations', ['person_id'], unique=False)
    op.create_index(op.f('ix_epay_observations_store_id'), 'epay_observations', ['store_id'], unique=False)
    op.create_index(op.f('ix_epay_observations_tenant_id'), 'epay_observations', ['tenant_id'], unique=False)
    op.create_table('grid_calculations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('month_id', sa.String(length=64), nullable=False),
    sa.Column('store_id', sa.String(length=64), nullable=False),
    sa.Column('person_id', sa.String(length=64), nullable=False),
    sa.Column('rule_pack_version', sa.String(length=32), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('inputs_hash', sa.String(length=64), nullable=False),
    sa.Column('outputs_hash', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['month_id'], ['months.id'], name=op.f('fk_grid_calculations_month_id_months')),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_grid_calculations_person_id_people')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_grid_calculations_store_id_stores')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_grid_calculations_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grid_calculations')),
    sa.UniqueConstraint('tenant_id', 'month_id', 'store_id', 'person_id', 'rule_pack_version', 'revision', name='uq_grid_calc_window')
    )
    op.create_index(op.f('ix_grid_calculations_month_id'), 'grid_calculations', ['month_id'], unique=False)
    op.create_index(op.f('ix_grid_calculations_person_id'), 'grid_calculations', ['person_id'], unique=False)
    op.create_index(op.f('ix_grid_calculations_store_id'), 'grid_calculations', ['store_id'], unique=False)
    op.create_index(op.f('ix_grid_calculations_tenant_id'), 'grid_calculations', ['tenant_id'], unique=False)
    op.create_table('person_day_absences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('month_id', sa.String(length=64), nullable=False),
    sa.Column('person_id', sa.String(length=64), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('OFF', 'LEAVE')", name=op.f('ck_person_day_absences_absence_status_enum')),
    sa.ForeignKeyConstraint(['month_id'], ['months.id'], name=op.f('fk_person_day_absences_month_id_months')),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_person_day_absences_person_id_people')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_person_day_absences_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_person_day_absences')),
    sa.UniqueConstraint('tenant_id', 'person_id', 'business_date', name='uq_absence_person_day')
    )
    op.create_index(op.f('ix_person_day_absences_month_id'), 'person_day_absences', ['month_id'], unique=False)
    op.create_index(op.f('ix_person_day_absences_person_id'), 'person_day_absences', ['person_id'], unique=False)
    op.create_index(op.f('ix_person_day_absences_tenant_id'), 'person_day_absences', ['tenant_id'], unique=False)
    op.create_table('sales_person_day',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('month_id', sa.String(length=64), nullable=False),
    sa.Column('store_id', sa.String(length=64), nullable=False),
    sa.Column('person_id', sa.String(length=64), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('generation', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['month_id'], ['months.id'], name=op.f('fk_sales_person_day_month_id_months')),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_sales_person_day_person_id_people')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_sales_person_day_store_id_stores')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_sales_person_day_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_person_day')),
    sa.UniqueConstraint('tenant_id', 'person_id', 'store_id', 'business_date', 'generation', name='uq_sales_person_day_generation')
    )
    op.create_index(op.f('ix_sales_person_day_month_id'), 'sales_person_day', ['month_id'], unique=False)
    op.create_index(op.f('ix_sales_person_day_person_id'), 'sales_person_day', ['person_id'], unique=False)
    op.create_index(op.f('ix_sales_person_day_store_id'), 'sales_person_day', ['store_id'], unique=False)
    op.create_index(op.f('ix_sales_person_day_tenant_id'), 'sales_person_day', ['tenant_id'], unique=False)
    op.create_table('site_day_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('month_id', sa.String(length=64), nullable=False),
    sa.Column('store_id', sa.String(length=64), nullable=False),
    sa.Column('person_id', sa.String(length=64), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('working_kind', sa.String(length=16), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'WORKING' AND working_kind IS NOT NULL) OR (status <> 'WORKING' AND working_kind IS NULL)", name=op.f('ck_site_day_assignments_working_kind_only_when_working')),
    sa.CheckConstraint("status IN ('WORKING', 'OFF', 'LEAVE')", name=op.f('ck_site_day_assignments_status_enum')),
    sa.CheckConstraint("working_kind IS NULL OR working_kind IN ('NORMAL', 'EXTRA_HOME', 'EXTRA_OTHER')", name=op.f('ck_site_day_assignments_working_kind_enum')),
    sa.ForeignKeyConstraint(['month_id'], ['months.id'], name=op.f('fk_site_day_assignments_month_id_months')),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_site_day_assignments_person_id_people')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_site_day_assignments_store_id_stores')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_site_day_assignments_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_site_day_assignments'))
    )
    op.create_index(op.f('ix_site_day_assignments_month_id'), 'site_day_assignments', ['month_id'], unique=False)
    op.create_index('ix_site_day_assignments_month_store', 'site_day_assignments', ['month_id', 'store_id', 'business_date'], unique=False)
    op.create_index(op.f('ix_site_day_assignments_person_id'), 'site_day_assignments', ['person_id'], unique=False)
    op.create_index(op.f('ix_site_day_assignments_store_id'), 'site_day_assignments', ['store_id'], unique=False)
    op.create_index(op.f('ix_site_day_assignments_tenant_id'), 'site_day_assignments', ['tenant_id'], unique=False)
    op.create_index('uq_person_day_one_working', 'site_day_assignments', ['tenant_id', 'person_id', 'business_date'], unique=True, sqlite_where=sa.text("status = 'WORKING'"), postgresql_where=sa.text("status = 'WORKING'"))
    op.create_index('uq_site_day_one_working', 'site_day_assignments', ['tenant_id', 'store_id', 'business_date'], unique=True, sqlite_where=sa.text("status = 'WORKING'"), postgresql_where=sa.text("status = 'WORKING'"))
    op.create_table('store_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('person_id', sa.String(length=64), nullable=False),
    sa.Column('store_id', sa.String(length=64), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name=op.f('ck_store_assignments_store_assignment_dates_valid')),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_store_assignments_person_id_people')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_store_assignments_store_id_stores')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_store_assignments_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_store_assignments'))
    )
    op.create_index(op.f('ix_store_assignments_person_id'), 'store_assignments', ['person_id'], unique=False)
    op.create_index('ix_store_assignments_person_window', 'store_assignments', ['tenant_id', 'person_id', 'effective_from'], unique=False)
    op.create_index(op.f('ix_store_assignments_store_id'), 'store_assignments', ['store_id'], unique=False)
    op.create_index(op.f('ix_store_assignments_tenant_id'), 'store_assignments', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_assignments_tenant_id'), table_name='store_assignments')
    op.drop_index(op.f('ix_store_assignments_store_id'), table_name='store_assignments')
    op.drop_index('ix_store_assignments_person_window', table_name='store_assignments')
    op.drop_index(op.f('ix_store_assignments_person_id'), table_name='store_assignments')
    op.drop_table('store_assignments')
    op.drop_index('uq_site_day_one_working', table_name='site_day_assignments', sqlite_where=sa.text("status = 'WORKING'"), postgresql_where=sa.text("status = 'WORKING'"))
    op.drop_index('uq_person_day_one_working', table_name='site_day_assignments', sqlite_where=sa.text("status = 'WORKING'"), postgresql_where=sa.text("status = 'WORKING'"))
    op.drop_index(op.f('ix_site_day_assignments_tenant_id'), table_name='site_day_assignments')
    op.drop_index(op.f('ix_site_day_assignments_store_id'), table_name='site_day_assignments')
    op.drop_index(op.f('ix_site_day_assignments_person_id'), table_name='site_day_assignments')
    op.drop_index('ix_site_day_assignments_month_store', table_name='site_day_assignments')
    op.drop_index(op.f('ix_site_day_assignments_month_id'), table_name='site_day_assignments')
    op.drop_table('site_day_assignments')
    op.drop_index(op.f('ix_sales_person_day_tenant_id'), table_name='sales_person_day')
    op.drop_index(op.f('ix_sales_person_day_store_id'), table_name='sales_person_day')
    op.drop_index(op.f('ix_sales_person_day_person_id'), table_name='sales_person_day')
    op.drop_index(op.f('ix_sales_person_day_month_id'), table_name='sales_person_day')
    op.drop_table('sales_person_day')
    op.drop_index(op.f('ix_person_day_absences_tenant_id'), table_name='person_day_absences')
    op.drop_index(op.f('ix_person_day_absences_person_id'), table_name='person_day_absences')
    op.drop_index(op.f('ix_person_day_absences_month_id'), table_name='person_day_absences')
    op.drop_table('person_day_absences')
    op.drop_index(op.f('ix_grid_calculations_tenant_id'), table_name='grid_calculations')
    op.drop_index(op.f('ix_grid_calculations_store_id'), table_name='grid_calculations')
    op.drop_index(op.f('ix_grid_calculations_person_id'), table_name='grid_calculations')
    op.drop_index(op.f('ix_grid_calculations_month_id'), table_name='grid_calculations')
    op.drop_table('grid_calculations')
    op.drop_index(op.f('ix_epay_observations_tenant_id'), table_name='epay_observations')
    op.drop_index(op.f('ix_epay_observations_store_id'), table_name='epay_observations')
    op.drop_index(op.f('ix_epay_observations_person_id'), table_name='epay_observations')
    op.drop_table('epay_observations')
    op.drop_index(op.f('ix_sheet_projection_runs_tenant_id'), table_name='sheet_projection_runs')
    op.drop_index(op.f('ix_sheet_projection_runs_store_id'), table_name='sheet_projection_runs')
    op.drop_table('sheet_projection_runs')
    op.drop_index(op.f('ix_sheet_bindings_tenant_id'), table_name='sheet_bindings')
    op.drop_index(op.f('ix_sheet_bindings_store_id'), table_name='sheet_bindings')
    op.drop_table('sheet_bindings')
    op.drop_index(op.f('ix_sales_store_day_tenant_id'), table_name='sales_store_day')
    op.drop_index(op.f('ix_sales_store_day_store_id'), table_name='sales_store_day')
    op.drop_table('sales_store_day')
    op.drop_index(op.f('ix_people_tenant_id'), table_name='people')
    op.drop_index(op.f('ix_people_home_store_id'), table_name='people')
    op.drop_table('people')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_stores_tenant_id'), table_name='stores')
    op.drop_table('stores')
    op.drop_index(op.f('ix_outbox_jobs_tenant_id'), table_name='outbox_jobs')
    op.drop_table('outbox_jobs')
    op.drop_index(op.f('ix_months_tenant_id'), table_name='months')
    op.drop_table('months')
    op.drop_index(op.f('ix_import_runs_tenant_id'), table_name='import_runs')
    op.drop_table('import_runs')
    op.drop_index(op.f('ix_export_runs_tenant_id'), table_name='export_runs')
    op.drop_table('export_runs')
    op.drop_index('ix_audit_tenant_entity', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_tenant_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('tenants')
    # ### end Alembic commands ###