"""composite tenant FKs and store targets

S1 attempt 2 remediation. This migration:

1. Replaces single-column foreign keys on ``stores`` and ``people`` with
   composite ``(tenant_id, target_id) -> (tenant_id, id)`` foreign keys.
   The composite shape is what enforces DB-level tenant integrity: a row
   in tenant X cannot reference a store owned by tenant Y because the
   composite columns would not match.
2. Adds the ``store_targets`` table that backs the v1 connector target
   records. The table is versioned by ``(year, month, kind, version)`` so
   superseding is auditable.
3. Adjusts the ``sheet_bindings`` unique constraint to include
   ``tenant_id`` so a store can only be bound to one Sheet per tenant.

Revision ID: b9fbb01f8cd0
Revises: 1e5c879d0851
Create Date: 2026-08-20 16:18:54.040499

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9fbb01f8cd0'
down_revision: str | None = '1e5c879d0851'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # The composite FKs reference ``stores(tenant_id, id)`` and
    # ``people(tenant_id, id)``. PostgreSQL requires the target to carry a
    # UNIQUE or PRIMARY KEY constraint that matches the column order. The PK
    # on ``id`` alone is not enough; we therefore add the composite unique
    # constraints first and the new FKs after.
    op.create_unique_constraint('uq_stores_tenant_id', 'stores', ['tenant_id', 'id'])
    op.create_unique_constraint('uq_people_tenant_id', 'people', ['tenant_id', 'id'])

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_people_home_store_id', table_name='people')
    op.drop_constraint('fk_people_home_store_id_stores', 'people', type_='foreignkey')
    op.create_foreign_key('fk_people_tenant_home_store', 'people', 'stores', ['tenant_id', 'home_store_id'], ['tenant_id', 'id'])
    op.drop_index('ix_site_day_assignments_person_id', table_name='site_day_assignments')
    op.drop_index('ix_site_day_assignments_store_id', table_name='site_day_assignments')
    op.drop_constraint('fk_site_day_assignments_store_id_stores', 'site_day_assignments', type_='foreignkey')
    op.drop_constraint('fk_site_day_assignments_person_id_people', 'site_day_assignments', type_='foreignkey')
    op.create_foreign_key('fk_site_day_assignments_tenant_store', 'site_day_assignments', 'stores', ['tenant_id', 'store_id'], ['tenant_id', 'id'])
    op.create_foreign_key('fk_site_day_assignments_tenant_person', 'site_day_assignments', 'people', ['tenant_id', 'person_id'], ['tenant_id', 'id'])
    op.drop_index('ix_store_assignments_person_id', table_name='store_assignments')
    op.drop_index('ix_store_assignments_store_id', table_name='store_assignments')
    op.drop_constraint('fk_store_assignments_person_id_people', 'store_assignments', type_='foreignkey')
    op.drop_constraint('fk_store_assignments_store_id_stores', 'store_assignments', type_='foreignkey')
    op.create_foreign_key('fk_store_assignments_tenant_store', 'store_assignments', 'stores', ['tenant_id', 'store_id'], ['tenant_id', 'id'])
    op.create_foreign_key('fk_store_assignments_tenant_person', 'store_assignments', 'people', ['tenant_id', 'person_id'], ['tenant_id', 'id'])
    op.drop_index('ix_sales_store_day_store_id', table_name='sales_store_day')
    op.drop_constraint('fk_sales_store_day_store_id_stores', 'sales_store_day', type_='foreignkey')
    op.create_foreign_key('fk_sales_store_day_tenant_store', 'sales_store_day', 'stores', ['tenant_id', 'store_id'], ['tenant_id', 'id'])
    op.drop_index('ix_sales_person_day_person_id', table_name='sales_person_day')
    op.drop_index('ix_sales_person_day_store_id', table_name='sales_person_day')
    op.drop_constraint('fk_sales_person_day_person_id_people', 'sales_person_day', type_='foreignkey')
    op.drop_constraint('fk_sales_person_day_store_id_stores', 'sales_person_day', type_='foreignkey')
    op.create_foreign_key('fk_sales_person_day_tenant_person', 'sales_person_day', 'people', ['tenant_id', 'person_id'], ['tenant_id', 'id'])
    op.create_foreign_key('fk_sales_person_day_tenant_store', 'sales_person_day', 'stores', ['tenant_id', 'store_id'], ['tenant_id', 'id'])
    op.drop_index('ix_person_day_absences_person_id', table_name='person_day_absences')
    op.drop_constraint('fk_person_day_absences_person_id_people', 'person_day_absences', type_='foreignkey')
    op.create_foreign_key('fk_person_day_absences_tenant_person', 'person_day_absences', 'people', ['tenant_id', 'person_id'], ['tenant_id', 'id'])
    op.drop_index('ix_epay_observations_person_id', table_name='epay_observations')
    op.drop_index('ix_epay_observations_store_id', table_name='epay_observations')
    op.drop_constraint('fk_epay_observations_store_id_stores', 'epay_observations', type_='foreignkey')
    op.drop_constraint('fk_epay_observations_person_id_people', 'epay_observations', type_='foreignkey')
    op.create_foreign_key('fk_epay_observations_tenant_store', 'epay_observations', 'stores', ['tenant_id', 'store_id'], ['tenant_id', 'id'])
    op.create_foreign_key('fk_epay_observations_tenant_person', 'epay_observations', 'people', ['tenant_id', 'person_id'], ['tenant_id', 'id'])
    op.drop_index('ix_grid_calculations_person_id', table_name='grid_calculations')
    op.drop_index('ix_grid_calculations_store_id', table_name='grid_calculations')
    op.drop_constraint('fk_grid_calculations_store_id_stores', 'grid_calculations', type_='foreignkey')
    op.drop_constraint('fk_grid_calculations_person_id_people', 'grid_calculations', type_='foreignkey')
    op.create_foreign_key('fk_grid_calculations_tenant_person', 'grid_calculations', 'people', ['tenant_id', 'person_id'], ['tenant_id', 'id'])
    op.create_foreign_key('fk_grid_calculations_tenant_store', 'grid_calculations', 'stores', ['tenant_id', 'store_id'], ['tenant_id', 'id'])
    op.drop_index('ix_sheet_bindings_store_id', table_name='sheet_bindings')
    op.drop_constraint('uq_sheet_binding_store', 'sheet_bindings', type_='unique')
    op.create_unique_constraint('uq_sheet_binding_tenant_store', 'sheet_bindings', ['tenant_id', 'store_id'])
    op.drop_constraint('fk_sheet_bindings_store_id_stores', 'sheet_bindings', type_='foreignkey')
    op.create_foreign_key('fk_sheet_bindings_tenant_store', 'sheet_bindings', 'stores', ['tenant_id', 'store_id'], ['tenant_id', 'id'])
    op.drop_index('ix_sheet_projection_runs_store_id', table_name='sheet_projection_runs')
    op.drop_constraint('fk_sheet_projection_runs_store_id_stores', 'sheet_projection_runs', type_='foreignkey')
    op.create_foreign_key('fk_sheet_projection_runs_tenant_store', 'sheet_projection_runs', 'stores', ['tenant_id', 'store_id'], ['tenant_id', 'id'])
    op.create_table('store_targets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('store_id', sa.String(length=64), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('MONTHLY_SALES', 'MONTHLY_UNITS', 'MONTHLY_ATTACH')", name=op.f('ck_store_targets_store_target_kind_enum')),
    sa.CheckConstraint('month BETWEEN 1 AND 12', name=op.f('ck_store_targets_store_target_month_in_range')),
    sa.ForeignKeyConstraint(['tenant_id', 'store_id'], ['stores.tenant_id', 'stores.id'], name='fk_store_targets_tenant_store'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_store_targets_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_store_targets')),
    sa.UniqueConstraint('tenant_id', 'store_id', 'year', 'month', 'kind', 'version', name='uq_store_target_window_version')
    )
    op.create_index(op.f('ix_store_targets_tenant_id'), 'store_targets', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_targets_tenant_id'), table_name='store_targets')
    op.drop_table('store_targets')
    op.create_index('ix_epay_observations_store_id', 'epay_observations', ['store_id'], unique=False)
    op.create_index('ix_epay_observations_person_id', 'epay_observations', ['person_id'], unique=False)
    op.drop_constraint('fk_epay_observations_tenant_store', 'epay_observations', type_='foreignkey')
    op.drop_constraint('fk_epay_observations_tenant_person', 'epay_observations', type_='foreignkey')
    op.create_foreign_key('fk_epay_observations_store_id_stores', 'epay_observations', 'stores', ['store_id'], ['id'])
    op.create_foreign_key('fk_epay_observations_person_id_people', 'epay_observations', 'people', ['person_id'], ['id'])
    op.create_index('ix_grid_calculations_store_id', 'grid_calculations', ['store_id'], unique=False)
    op.create_index('ix_grid_calculations_person_id', 'grid_calculations', ['person_id'], unique=False)
    op.drop_constraint('fk_grid_calculations_tenant_store', 'grid_calculations', type_='foreignkey')
    op.drop_constraint('fk_grid_calculations_tenant_person', 'grid_calculations', type_='foreignkey')
    op.create_foreign_key('fk_grid_calculations_store_id_stores', 'grid_calculations', 'stores', ['store_id'], ['id'])
    op.create_foreign_key('fk_grid_calculations_person_id_people', 'grid_calculations', 'people', ['person_id'], ['id'])
    op.create_index('ix_people_home_store_id', 'people', ['home_store_id'], unique=False)
    op.drop_constraint('fk_people_tenant_home_store', 'people', type_='foreignkey')
    op.create_foreign_key('fk_people_home_store_id_stores', 'people', 'stores', ['home_store_id'], ['id'])
    op.create_index('ix_person_day_absences_person_id', 'person_day_absences', ['person_id'], unique=False)
    op.drop_constraint('fk_person_day_absences_tenant_person', 'person_day_absences', type_='foreignkey')
    op.create_foreign_key('fk_person_day_absences_person_id_people', 'person_day_absences', 'people', ['person_id'], ['id'])
    op.create_index('ix_sales_person_day_store_id', 'sales_person_day', ['store_id'], unique=False)
    op.create_index('ix_sales_person_day_person_id', 'sales_person_day', ['person_id'], unique=False)
    op.drop_constraint('fk_sales_person_day_tenant_store', 'sales_person_day', type_='foreignkey')
    op.drop_constraint('fk_sales_person_day_tenant_person', 'sales_person_day', type_='foreignkey')
    op.create_foreign_key('fk_sales_person_day_store_id_stores', 'sales_person_day', 'stores', ['store_id'], ['id'])
    op.create_foreign_key('fk_sales_person_day_person_id_people', 'sales_person_day', 'people', ['person_id'], ['id'])
    op.create_index('ix_sales_store_day_store_id', 'sales_store_day', ['store_id'], unique=False)
    op.drop_constraint('fk_sales_store_day_tenant_store', 'sales_store_day', type_='foreignkey')
    op.create_foreign_key('fk_sales_store_day_store_id_stores', 'sales_store_day', 'stores', ['store_id'], ['id'])
    op.create_index('ix_sheet_bindings_store_id', 'sheet_bindings', ['store_id'], unique=False)
    op.drop_constraint('uq_sheet_binding_tenant_store', 'sheet_bindings', type_='unique')
    op.create_unique_constraint('uq_sheet_binding_store', 'sheet_bindings', ['store_id'])
    op.drop_constraint('fk_sheet_bindings_tenant_store', 'sheet_bindings', type_='foreignkey')
    op.create_foreign_key('fk_sheet_bindings_store_id_stores', 'sheet_bindings', 'stores', ['store_id'], ['id'])
    op.create_index('ix_sheet_projection_runs_store_id', 'sheet_projection_runs', ['store_id'], unique=False)
    op.drop_constraint('fk_sheet_projection_runs_tenant_store', 'sheet_projection_runs', type_='foreignkey')
    op.create_foreign_key('fk_sheet_projection_runs_store_id_stores', 'sheet_projection_runs', 'stores', ['store_id'], ['id'])
    op.create_index('ix_site_day_assignments_store_id', 'site_day_assignments', ['store_id'], unique=False)
    op.create_index('ix_site_day_assignments_person_id', 'site_day_assignments', ['person_id'], unique=False)
    op.drop_constraint('fk_site_day_assignments_tenant_store', 'site_day_assignments', type_='foreignkey')
    op.drop_constraint('fk_site_day_assignments_tenant_person', 'site_day_assignments', type_='foreignkey')
    op.create_foreign_key('fk_site_day_assignments_store_id_stores', 'site_day_assignments', 'stores', ['store_id'], ['id'])
    op.create_foreign_key('fk_site_day_assignments_person_id_people', 'site_day_assignments', 'people', ['person_id'], ['id'])
    op.create_index('ix_store_assignments_store_id', 'store_assignments', ['store_id'], unique=False)
    op.create_index('ix_store_assignments_person_id', 'store_assignments', ['person_id'], unique=False)
    op.drop_constraint('fk_store_assignments_tenant_store', 'store_assignments', type_='foreignkey')
    op.drop_constraint('fk_store_assignments_tenant_person', 'store_assignments', type_='foreignkey')
    op.create_foreign_key('fk_store_assignments_store_id_stores', 'store_assignments', 'stores', ['store_id'], ['id'])
    op.create_foreign_key('fk_store_assignments_person_id_people', 'store_assignments', 'people', ['person_id'], ['id'])
    op.drop_constraint('uq_people_tenant_id', 'people', type_='unique')
    op.drop_constraint('uq_stores_tenant_id', 'stores', type_='unique')
    # ### end Alembic commands ###